<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>netcoreapp3.0</TargetFramework>
		<UserSecretsId>2b993030-8a93-44e2-999c-c6820ff24084</UserSecretsId>
	</PropertyGroup>
	<ItemGroup>
		<Compile Remove="Uploads\Facilties\**" />
		<Compile Remove="Uploads\NewFolder\**" />
		<Content Remove="Uploads\Facilties\**" />
		<Content Remove="Uploads\NewFolder\**" />
		<EmbeddedResource Remove="Uploads\Facilties\**" />
		<EmbeddedResource Remove="Uploads\NewFolder\**" />
		<None Remove="Uploads\Facilties\**" />		
		<None Remove="Uploads\NewFolder\**" />
	</ItemGroup>

	
	<ItemGroup>
		<PackageReference Include="log4net" Version="2.0.8" />
		<PackageReference Include="MicroKnights.Log4NetAdoNetAppender" Version="1.0.2" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="2.2.0" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.6.0" />
		<PackageReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="log4net.config">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Uploads\Facilities\NewFolder\" />
		<Folder Include="Uploads\Finance\NewFolder\" />
		<Folder Include="Uploads\Improvement\NewFolder\" />
		<Folder Include="Uploads\Land\NewFolder\" />
		<Folder Include="Uploads\HandoverDocuments\" />
		<Folder Include="Uploads\Faults\" />
		<Folder Include="Uploads\SnagList\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\MAM.BusinessLayer\MAM.BusinessLayer.csproj" />
	</ItemGroup>
</Project>
