CREATE TABLE [dbo].[Facilities] (
    [Id]             INT           IDENTITY (1, 1) NOT NULL,
    [Name]           VARCHAR (500) NOT NULL,
    [FileReference]  VARCHAR (500) NOT NULL,
    [Type]           VARCHAR (500) NOT NULL,
    [ClientCode]     VARCHAR (500) NOT NULL,
    [Status]         VARCHAR (500) NOT NULL,
    [UserDepartment] VARCHAR (500) NULL,
    [VestedType]     VARCHAR (50)  NULL,
    [Survey]         VARCHAR (500) NULL,
    [CapturerId]     INT           NOT NULL,
    [LandId]         INT           NULL,
    [FinanceId]      INT           NULL,
    [CreatedDate]    DATETIME      NOT NULL,
    [ModifierId]     INT           NULL,
    [ModifiedDate]   DATETIME      NULL,
    [ApproverId]     INT           NULL,
    [ApprovedDate]   DATETIME      NULL,
    [VerifierId]     INT           NULL,
    [SingedOffDate]  DATETIME      NULL,
    CONSTRAINT [PK_Facility] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Facilities_Users] FOREIGN KEY ([CapturerId]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [FK_Facility_Finance] FOREIGN KEY ([FinanceId]) REFERENCES [dbo].[Finances] ([Id]),
    CONSTRAINT [FK_Facility_Land] FOREIGN KEY ([LandId]) REFERENCES [dbo].[Lands] ([Id])
);

