CREATE TABLE [dbo].[OperationPlans] (
    [Id]                                 INT           IDENTITY (1, 1) NOT NULL,
    [UserImmovableAssetManagementPlanId] INT           NULL,
    [DistrictRegion]                     VARCHAR (500) NULL,
    [Town]                               VARCHAR (500) NULL,
    [ServiceDescription]                 VARCHAR (500) NULL,
    [BudgetType]                         VARCHAR (500) NULL,
    [LocalMunicipality]                  VARCHAR (500) NULL,
    [AssetDescription]                   VARCHAR (500) NULL,
    [RepairDescription]                  VARCHAR (500) NULL,
    [PrioityServiceReanking]             VARCHAR (500) NULL,
    [StreetDescription]                  VARCHAR (500) NULL,
    [PropertyDescription]                VARCHAR (500) NULL,
    [LeaseType]                          VARCHAR (500) NULL,
    [NoofParkingBays]                    INT           NULL,
    [UsableSpace]                        FLOAT (53)    NULL,
    [ConstructionArea]                   FLOAT (53)    NULL,
    [LeaseStartDate]                     DATETIME      NULL,
    [LeaseEndDate]                       DATETIME      NULL,
    [RentalPmPa]                         MONEY         NULL,
    [InitialNeedYear]                    INT           NULL,
    [Status]                             VARCHAR (500) NULL,
    [TotalAmountRequired]                MONEY         NULL,
    [CashFlowYear1]                      MONEY         NULL,
    [CashFlowYear2]                      MONEY         NULL,
    [CashFlowYear3]                      MONEY         NULL,
    [CashFlowYear4]                      MONEY         NULL,
    [CashFlowYear5]                      MONEY         NULL,
    [ExtentofLand]                       FLOAT (53)    NULL,
    [TempleteNumber]                     FLOAT (53)    NULL,
    [Comment]                            VARCHAR (500) NULL,
    [Leased]                             BIT           NULL,
    CONSTRAINT [PK_OperationPlan] PRIMARY KEY CLUSTERED ([Id] ASC)
);

