CREATE TABLE [dbo].[Projects] (
    [Id]                      INT           IDENTITY (1, 1) NOT NULL,
    [OrderNumber]             VARCHAR (50)  NOT NULL,
    [District]                VARCHAR (100) NULL,
    [PropertyId]              INT           NULL,
    [Name]                    VARCHAR (500) NULL,
    [StartDate]               DATETIME      NULL,
    [PracticalCompletionDate] DATETIME      NULL,
    [PlannedDuration]         VARCHAR (500) NULL,
    [ScopeofWork]             VARCHAR (500) NULL,
    [HasFinancials]           BIT           NULL,
    [HasParentProject]        BIT           NULL,
    [ParentProjectId]         INT           NULL,
    [Amount]                  FLOAT (53)    NULL,
    [Account]                 BIGINT        NULL,
    [ManagedBy]               VARCHAR (50)  NULL,
    [EmployeeName]            VARCHAR (100) NULL,
    [EmployeeNumber]          BIGINT        NULL,
    [ContactName]             VARCHAR (100) NULL,
    [ContactNumber]           VARCHAR (20)  NULL,
    [BusinessName]            VARCHAR (500) NULL,
    [BusinessRegNumber]       VARCHAR (100) NULL,
    [CreatedDate]             DATETIME      NULL,
    [ModifiedDate]            DATETIME      NULL,
    [IsDeleted]               BIT           NULL,
    [Status]                  VARCHAR (100) NULL,
    CONSTRAINT [PK_Projects] PRIMARY KEY CLUSTERED ([Id] ASC)
);

