CREATE TABLE [dbo].[Properties] (
    [Id]                                 INT           IDENTITY (1, 1) NOT NULL,
    [UserImmovableAssetManagementPlanId] INT           NOT NULL,
    [TempleteNumber]                     FLOAT (53)    NULL,
    [FileReferenceNo]                    VARCHAR (500) NULL,
    [SerialNo]                           VARCHAR (500) NULL,
    [DistrictRegion]                     VARCHAR (500) NULL,
    [Town]                               VARCHAR (500) NULL,
    [LocalAuthority]                     VARCHAR (500) NULL,
    [LocalMunicipality]                  VARCHAR (500) NULL,
    [AssetDescription]                   VARCHAR (500) NULL,
    [OldStreetAddress]                   VARCHAR (500) NULL,
    [CurrentStreetAddress]               VARCHAR (500) NULL,
    [PropertyDescription]                VARCHAR (500) NULL,
    [AssetType]                          VARCHAR (500) NULL,
    [NoofParkingBays]                    INT           NULL,
    [NoofParkingBaysAllocated]           INT           NULL,
    [UsableAllocatedSpace]               FLOAT (53)    NULL,
    [LettableSpace]                      FLOAT (53)    NULL,
    [ExtentofLand]                       FLOAT (53)    NULL,
    [RentalPM]                           MONEY         NULL,
    [RentalPA]                           MONEY         NULL,
    [MunicipalUtilityServiceTotal]       MONEY         NULL,
    [PropertyRatesTaxes]                 MONEY         NULL,
    [OperationalCosts]                   MONEY         NULL,
    [RequiredPerformanceStandard]        VARCHAR (500) NULL,
    [Accessibility]                      VARCHAR (500) NULL,
    [ConditionRating]                    VARCHAR (50)  NULL,
    [SuitabilityIndex]                   VARCHAR (500) NULL,
    [OperatingPerformanceIndex]          VARCHAR (500) NULL,
    [FunctionalPerformanceIndex]         VARCHAR (500) NULL,
    [LeaseStartDate]                     DATETIME      NULL,
    [LeaseEndDate]                       DATETIME      NULL,
    [LeaseTerm]                          VARCHAR (500) NULL,
    [Comment]                            VARCHAR (500) NULL,
    CONSTRAINT [PK_Property] PRIMARY KEY CLUSTERED ([Id] ASC)
);

